### ISSUE TITLE
Add FTP class/function to upload sitemap to server

### ISSUE THREAD

**Issue by lablnet** [Usman-Naeem/sitemap#2]
Add FTP class/function to upload sitemap to server

1. Create new file`_ftp.py`
2. You can import `config` module that build in with this project
3. And put config option in config file.

Thanks

**Comment by Krishna-Sivakumar** [comment]
Can I work on this? 
and can you provide more details too?

**Comment by lablnet** [comment]
> Can I work on this?
> and can you provide more details too?

yes you can

basically the script generate sitemaps, we want that the ftp class accept file as argument and upload it using ftp to targeted directory

**Comment by Krishna-Sivakumar** [comment]
> basically the script generate sitemaps, we want that the ftp class accept file as argument and upload it using ftp to targeted directory

So, the ftp class argument would be the path to the file right?

**Comment by aniket786333** [comment]
> Add FTP class/function to upload sitemap to server
> 
> 1. Create new file`_ftp.py`
> 2. You can import `config` module that build in with this project
> 3. And put config option in config file.
> 
> 
> Thanks
May I work with you??

**Comment by Usman-Naeem** [comment]
> > Thanks
> > May I work with you??

@aniket786333 You Created 6 Repositories Today, and have no other code. I am sorry but you are not welcome to code here.

**Comment by lablnet** [comment]
> > basically the script generate sitemaps, we want that the ftp class accept file as argument and upload it using ftp to targeted directory
> 
> So, the ftp class argument would be the path to the file right?

Yes

**Comment by prikmm** [comment]
> > Can I work on this?
> > and can you provide more details too?
> 
> yes you can
> 
> basically the script generate sitemaps, we want that the ftp class accept file as argument and upload it using ftp to targeted directory

Hello,

Can you specify what the targeted directory is?
Is it the google servers? And If yes, then will I need google search console API or is there another method, since I am not able to find one?

Thank you

**Comment by lablnet** [comment]
> > > Can I work on this?
> > > and can you provide more details too?
> > 
> > 
> > yes you can
> > basically the script generate sitemaps, we want that the ftp class accept file as argument and upload it using ftp to targeted directory
> 
> Hello,
> 
> Can you specify what the targeted directory is?
> Is it the google servers? And If yes, then will I need google search console API or is there another method, since I am not able to find one?
> 
> Thank you

FTP have noting to do with google, FTP simply mean file transfer protocol, and the path provided with class constructor

**Comment by rajat1401** [comment]
Hi @lablnet I have created a [PR](https://github.com/Usman-Naeem/sitemap/pull/4) as a part of Hacktoberfest 2020 for the above issue. Please review it.
